# Generated by Django 3.1 on 2020-09-07 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopify_sync', '0003_auto_20200818_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shopify_sync_errorsynclog', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shopify_sync_errorsynclog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error Sync Log',
                'verbose_name_plural': 'Errors Sync Log',
            },
        ),
    ]
